### ISSUE TITLE
Server crashed when simple auto restart tried to take effect.

### ISSUE THREAD

**Issue by timmbobb** [teunjojo/SimpleAutoRestart#11]
config:
# The hour and minute when the server should restart (24 hour format)
restartTime:
- '10:00'
- '22:00'
# Add multiple times by adding a new line like: - '12:00'

# Configure message and the corresponding pre-warning time in seconds
messages:
  '0': 'Restarting now'
  '1': 'Restarting in 1 second'
  '2': 'Restarting in 2 seconds'
  '3': 'Restarting in 3 seconds'
  '60': 'Restarting in 1 minute'
  '120': 'Restarting in 2 minutes'
  '180': 'Restarting in 3 minutes'
  '300': 'Restarting in 5 minutes'

titles: 
  '300' : '§l§4Warning'
  '3' : '§l§4Warning'

subtitles:
  '300' : "§6Restarting in 5 minutes"
  '3' : "§6Restarting now..."

logs:
[08Apr2024 09:30:50.826] [Craft Scheduler Thread - 19/INFO] [net.milkbowl.vault.Vault/]: [Vault] Checking for Updates ... 
[08Apr2024 09:30:50.932] [Craft Scheduler Thread - 19/INFO] [net.milkbowl.vault.Vault/]: [Vault] No new version available
[08Apr2024 09:55:00.973] [Timer-1/INFO] [/]: Restarting in 5 minutes[m
[08Apr2024 09:57:00.972] [Timer-1/INFO] [/]: Restarting in 3 minutes[m
[08Apr2024 09:58:00.972] [Timer-1/INFO] [/]: Restarting in 2 minutes[m
[08Apr2024 09:59:00.972] [Timer-1/INFO] [/]: Restarting in 1 minute[m
[08Apr2024 09:59:57.973] [Timer-1/INFO] [/]: Restarting in 3 seconds[m
[08Apr2024 09:59:58.972] [Timer-1/INFO] [/]: Restarting in 2 seconds[m
[08Apr2024 09:59:59.973] [Timer-1/INFO] [/]: Restarting in 1 second[m
[08Apr2024 10:00:00.973] [Timer-1/INFO] [/]: Startup script './start.sh' does not exist! Stopping server.
[08Apr2024 10:00:00.973] [Timer-1/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[08Apr2024 10:00:00.973] [Timer-1/INFO] [EssentialsChat/]: Disabling EssentialsChat v2.21.0-dev+75-76a513a
[08Apr2024 10:00:00.975] [Timer-1/INFO] [Essentials/]: Disabling Essentials v2.21.0-dev+75-76a513a
[08Apr2024 10:00:00.975] [Timer-1/INFO] [net.milkbowl.vault.Vault/]: [Vault] [Economy] Essentials Economy unhooked.
[08Apr2024 10:00:00.975] [Timer-1/ERROR] [Essentials/]: There's a good chance you're reloading your server right now. If that's the case, why do you hate yourself? Expect no support from the EssentialsX team when using /reload.
[08Apr2024 10:00:00.977] [Timer-1/INFO] [com.teunjojo.SimpleAutoRestart/]: [SimpleAutoRestart] Disabling SimpleAutoRestart v2.5.1
[08Apr2024 10:00:00.978] [Timer-1/INFO] [net.milkbowl.vault.Vault/]: [Vault] Disabling Vault v1.7.3-b131
[08Apr2024 10:00:00.978] [Timer-1/INFO] [com.gmail.nossr50.mcMMO/]: [mcMMO] Disabling mcMMO v2.1.231
[08Apr2024 10:00:00.978] [Timer-1/INFO] [com.gmail.nossr50.mcMMO/]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[08Apr2024 10:00:00.978] [Timer-1/INFO] [com.gmail.nossr50.mcMMO/]: [mcMMO] Saving mcMMOPlayers... (0)
[08Apr2024 10:00:00.978] [Timer-1/INFO] [com.gmail.nossr50.mcMMO/]: [mcMMO] Finished save operation for 0 players!
[08Apr2024 10:00:00.998] [Timer-1/INFO] [me.neznamy.tab.platforms.bukkit.BukkitTAB/]: [TAB] Disabling TAB v4.0.3
[08Apr2024 10:00:01.010] [Timer-1/INFO] [/]: [TAB] [38;2;85;255;85mDisabled in 12ms[m
[08Apr2024 10:00:01.011] [Timer-1/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Disabling LuckPerms v5.4.121
[08Apr2024 10:00:01.011] [Timer-1/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Starting shutdown process...
[08Apr2024 10:00:01.030] [Timer-1/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Closing storage...
[08Apr2024 10:00:01.075] [Timer-1/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Goodbye!
[08Apr2024 10:00:01.076] [Timer-1/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[08Apr2024 10:00:01.176] [Timer-1/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[08Apr2024 10:00:01.177] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.fixPointers(LongLinkedOpenHashSet.java:812) ~[fastutil-8.5.12.jar%23145!/:?]
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.shiftKeys(LongLinkedOpenHashSet.java:489) ~[fastutil-8.5.12.jar%23145!/:?]
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:566) ~[fastutil-8.5.12.jar%23145!/:?]
	at net.minecraft.world.level.lighting.LeveledPriorityQueue.m_278178_(LeveledPriorityQueue.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.world.level.lighting.DynamicGraphMinFixedPoint.m_75588_(DynamicGraphMinFixedPoint.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.level.TickingTracker.m_184145_(TickingTracker.java:109) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:303) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:617) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:299) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:997) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:986) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:960) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:876) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23222!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08Apr2024 10:00:01.209] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID ea4be03b-76a1-4ccc-9ab7-00b169b7ce07
[08Apr2024 10:00:01.210] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /minecraft/./crash-reports/crash-2024-04-08_10.00.01-server.txt

**Comment by teunjojo** [comment]
As it says in the logs, you have have a restart script. For more information: [read this](https://www.spigotmc.org/threads/spigot-restart-script-help.158611/)

**Comment by timmbobb** [comment]
Yeah, ended up not being able to do this as I'm using docker compose and
containers to run the server, when the minecraft process ends, it kills the
container preventing the spigot restart script from going off.
